COUNTRIES = ['us', 'uk']
COUNTRY_PROXY_ADDRESSES_KEY_PREFIX = "country_proxy_addresses"
INVALID_PROXY_KEY = "invalid_proxies"
INVALID_TIME_IN_SEC = 21600
FLASK_HOST = "localhost"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
DATA_FILE_NAME = "MOCK_PROXIES_DATA_10000.json"
